### ISSUE TITLE
2.4 version still around somewhere?

### ISSUE THREAD

**Issue by Martimiz** [unclecheese/silverstripe-kickassets#13]
Hi
I realize that an early version missing from this repo isn't really an 'issue', so I appologize in advance if you feel this post inappropriate, but I'm in a bit of a fix...  

I've recently taken over a hughe 2.4 site that uses a(n obviously older) version of kickassets. Now it looks like it is not possible to rename folders accidentaly named 'new-folder'. I hoped that it might be a bug in the version used for that original site that had since been fixed, but now I fear the module is no longer around. Unfortunately updating to 3.1 is not yet an option for this hughe site...

Do you by chance remember if there ever used to be such an issue (and how it might be solved)? Now if you select a folder and click edit, it just seems to load the contents... In the mean time the client has created multiple new-folder folders :) Any help very much appreciated!

**Comment by camspiers** [comment]
https://github.com/unclecheese/KickAssets
