### ISSUE TITLE
Speech bubble icon

### ISSUE THREAD

**Issue by jonom** [unclecheese/silverstripe-kickassets#15]
This is module is a thing of beauty UC. Thank you so much for sharing it.

I noticed the icon in the sidebar of the CMS is a speech bubble - think that would be better as a pair of files or a folder?

![screen shot 2015-11-13 at 3 27 09 pm](https://cloud.githubusercontent.com/assets/1079425/11160135/0fae261c-8a1b-11e5-9804-453eb647bf49.png)

**Comment by unclecheese** [comment]
Thanks, Jono.. I think updating the icon is one of many commits I've made for 3.1 release coming soon.

**Comment by stevie-mayhew** [comment]
[plug] @jonom for now you can use the great https://github.com/Rhym/silverstripe-cms-theme to get around this and end up with a beautiful left navigation ![like this](http://i.imgur.com/LQ86IcP.png) [/end plug]

**Comment by unclecheese** [comment]
New icon has been released in 3.1

**Comment by jonom** [comment]
Sweet, thanks @unclecheese. Cheers for the recommendation too @stevie-mayhew I'll check that out
