### ISSUE TITLE
Extensions list seems to be empty

### ISSUE THREAD

**Issue by lhasselb** [unclecheese/silverstripe-kickassets#16]
First let me say thank you for developing this awesome module. 

It seems with a recent change there is a minor problem within the function JSONConfig (KickAssets.php, starting line 422) .

		$allExts = $r->getVar('allowedExtensions') ?
				   explode(',', $r->getVar('allowedExtensions')) :
				   File::config()->allowed_extensions;

$allExts seems to be 'null' (string null) instead of null when allowedExtensions is not present.

Something like

		$allExts = $r->getVar('allowedExtensions') != 'null' ?
				   explode(',', $r->getVar('allowedExtensions')) :
				   File::config()->allowed_extensions;

could help but there might be better solutions.

**Comment by unclecheese** [comment]
Thanks. This should be fixed in the master branch, soon to be tagged.

**Comment by unclecheese** [comment]
Sorted in the 3.1 release
