### ISSUE TITLE
Warning: No route matches path 

### ISSUE THREAD

**Issue by cjsewell** [unclecheese/silverstripe-kickassets#17]
From admin, when clicking the Browse Files item, I get a blank dialog pop up.
In the javascript console I get the warning 
```
Warning: No route matches path "/admin/kickassets/show/0?allowSelection=0&maxSelection=0&folderID=0&canUpload=1&canDelete=1&canEdit=1&canCreateFolder=1&canBrowse=1&allowedTypes=file%2Cimage%2Cfolder". 
Make sure you have <Route path="/admin/kickassets/show/0?allowSelection=0&maxSelection=0&folderID=0&canUpload=1&canDelete=1&canEdit=1&canCreateFolder=1&canBrowse=1&allowedTypes=file%2Cimage%2Cfolder">
somewhere in your routes
```

Any ideas?

**Comment by unclecheese** [comment]
I haven't seen this one before, and I can't replicate it. What hostname are you using? Anything unusual going on? Browser? Are you on the 3.1 release?

**Comment by cjsewell** [comment]
Hi, I have tested on a couple of sites running on a local Apache install:
```
http://local.xxxxxx-xx.govt.nz/admin/pages/
http://client.clientdomin.com.vcap.me/admin/pages/
http://127.0.0.1/client/clientdomin.com/admin/pages/
http://localhost/client-website/
```
We have one site in testing which is not local, with a URL like
`http://uat.client.com/admin/pages/`

All exhibit the same issue.

Versions are are:
```
"silverstripe/cms": "3.1.15",
"silverstripe/framework": "3.1.15",
"unclecheese/silverstripe-kickassets": "^3.1"
```
and
```
"silverstripe/cms": "3.2.1",
"silverstripe/framework": "3.2.1",
"unclecheese/silverstripe-kickassets": "^3.1"
```

Tested on Windows 10 with
Chrome 46
Firefox 42 
Edge 13.1

No other issues with the sites, we do have a fair few our "default modules" installed.
I might try a clean SS install with kickassts. See if that works, then add the other modules one by one,  one of them might be breaking it, but as far as I know they don't add additional JS in admin.

Will let you know how that goes!

**Comment by unclecheese** [comment]
Interesting. Does the demo work for you? http://modules.unclecheeseproductions.com (kickassets/kickassets)

**Comment by cjsewell** [comment]
Yes it does? Works perfect.

I just done a clean install test 
```
composer create-project silverstripe/installer kickassetstest 3.2.1
cd kickassetstest
composer require unclecheese/silverstripe-kickassets
```
Went through the setup steps, logged in and..... got the same issue..

Is there any Apache/PHP requirements the I'm possibly missing?

**Comment by unclecheese** [comment]
The only variable that I can see so far is that you're on Windows, and I haven't tested on that, really. I've just done a bit of IE testing with Browserstack, but that isn't serving the page with Windows -- it was using my local server.

Curious -- the leading slash might be an issue. If you look at the source code, in the definition for `windows.KickAssetsConfig`, check the value of `baseRoute`.

**Comment by cjsewell** [comment]
On my local clean install, baseRoute does not have a leading slash:
`window.KickAssetsConfig = {"baseRoute":"admin\/kickassets\/","maxFilesize":134,"allowedExtensions":".ace,.arc,.arj,.asf,.au,.avi,.bmp,.bz2,.cab,.cda,.css,.csv,.dmg,.doc,.docx,.dotx,.dotm,.flv,.gif,.gpx,.gz,.hqx,.ico,.jar,.jpeg,.jpg,.js,.kml,.m4a,.m4v,.mid,.midi,.mkv,.mov,.mp3,.mp4,.mpa,.mpeg,.mpg,.ogg,.ogv,.pages,.pcx,.pdf,.pkg,.png,.pps,.ppt,.pptx,.potx,.potm,.ra,.ram,.rm,.rtf,.sit,.sitx,.tar,.tgz,.tif,.tiff,.txt,.wav,.webm,.wma,.wmv,.xls,.xlsx,.xltx,.xltm,.zip,.zipx","thumbnailsDir":"dropzone\/images\/file-icons","langNewFolder":"NewFolder","iconSize":64,"thumbnailWidth":198,"thumbnailHeight":132,"defaultSort":"newest","defaultView":"grid","maxCacheSize":500000,"folderExtension":" ","allowSelection":false,"maxSelection":0,"canUpload":true,"canDelete":true,"canEdit":true,"canCreateFolder":true,"allowedTypes":["file","image","folder"]};`

However, neither does modules.unclecheeseproductions.com
`window.KickAssetsConfig = {"baseRoute":"admin\/kickassets\/","maxFilesize":2,"allowedExtensions":".ace,.arc,.arj,.asf,.au,.avi,.bmp,.bz2,.cab,.cda,.css,.csv,.dmg,.doc,.docx,.dotx,.dotm,.flv,.gif,.gpx,.gz,.hqx,.htm,.html,.ico,.jar,.jpeg,.jpg,.js,.kml,.m4a,.m4v,.mid,.midi,.mkv,.mov,.mp3,.mp4,.mpa,.mpeg,.mpg,.ogg,.ogv,.pages,.pcx,.pdf,.pkg,.png,.pps,.ppt,.pptx,.potx,.potm,.ra,.ram,.rm,.rtf,.sit,.sitx,.swf,.tar,.tgz,.tif,.tiff,.txt,.wav,.webm,.wma,.wmv,.xhtml,.xls,.xlsx,.xltx,.xltm,.xml,.zip,.zipx","thumbnailsDir":"dropzone\/images\/file-icons","langNewFolder":"NewFolder","iconSize":64,"thumbnailWidth":198,"thumbnailHeight":132,"defaultSort":"newest","defaultView":"grid","maxCacheSize":500000,"folderExtension":" ","allowSelection":false,"maxSelection":0,"canUpload":true,"canDelete":true,"canEdit":true,"canCreateFolder":true,"allowedTypes":["file","image","folder"]};`

**Comment by unclecheese** [comment]
Hmm.. Just for fun, try removing the query string from the URL, and leave the traling slash, so it's like: `http://myhostname.local/admin/kickassets/show/0`

Any joy?

**Comment by cjsewell** [comment]
Same issue if I do that.

I have been doing some more playing around, and it seems to be related to SS being installed in a subfolder rather than web root.

eg 
http://localhost/kickassetstest/admin/kickassets/show/0   < Installed in to the `kickassetstest` sub folder and doesn't work
http://kickassetstest.vcap.me/admin/kickassets/show/0  < installed at the web root and works perfectly

**Comment by unclecheese** [comment]
Awesome. I'm going to run a test. What does your base tag say?

**Comment by cjsewell** [comment]
On the broken one
```html
<base href="http://localhost/kickassetstest/">
```
On the working one
```html
<base href="http://kickassetstest.vcap.me/">
```

**Comment by cjsewell** [comment]
OK found a fix.
Prefixing baseRoute with Director::baseURL() fixes it while still working on sites installed in web root.

I  will make a pull request shortly!

Thanks for your help.
