### ISSUE TITLE
Unexpected T_OBJECT_OPERATOR 

### ISSUE THREAD

**Issue by mschilder** [unclecheese/silverstripe-kickassets#34]
Hi! After running:

```
composer require unclecheese/silverstripe-kickassets
```

And:

````
/dev/build
````

I receive this error:

Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /.../kickassets/code/KickAssets.php on line 198

What can this be?!

PS. I'm using SilverStripe 3.2

**Comment by stecman** [comment]
@mschilder sounds like you're trying to run this module under PHP 5.3. That error comes from the use of 5.4 syntax (class member access on instantiation, e.g. `(new Foo)->bar()`). PHP 5.4 is [listed as a requirement in this project's composer.json](https://github.com/unclecheese/silverstripe-kickassets/blob/master/composer.json#L15).

If you have to get this running under 5.3, [here's a patch to make `3.1.2` 5.3 compatible](https://gist.github.com/stecman/c4eb8080a6ed6af772de). To apply it, run the following from your project root:

```
curl https://gist.githubusercontent.com/stecman/c4eb8080a6ed6af772de/raw/7c234d0ca147f6a423f6963be4c813894bf42b8d/kickassets-3.1.2-php53.patch -O
patch -p1 < kickassets-3.1.2-php53.patch
```

**Comment by mschilder** [comment]
That's probably it, thanks for pointing this out. Will set my environment to PHP 5.4 and try again!
