### ISSUE TITLE
Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by hpeide** [unclecheese/silverstripe-kickassets#35]
I'm getting a:
Notice: Undefined index: HTTP_USER_AGENT in */kickassets/_config.php on line 6

PHP 5.6.16 and PHP 5.5.30.

**Comment by unclecheese** [comment]
That's odd. What browser are you using?

**Comment by banglashi** [comment]
I noticed this too, in my case it happens when running via terminal, for example using [sspak](https://github.com/silverstripe/sspak) or similar, the request doesn't get a $_SERVER['HTTP_USER_AGENT']. A simple fix like this could do perhaps.
```php
if(isset($_SERVER['HTTP_USER_AGENT']) && !preg_match('/(?i)msie [5-9]/',$_SERVER['HTTP_USER_AGENT'])) {
	CMSMenu::remove_menu_item('AssetAdmin');
}
```

**Comment by Cheddam** [comment]
#38 fixes this issue!
