### ISSUE TITLE
Newb Install

### ISSUE THREAD

**Issue by tekurinui** [unclecheese/silverstripe-kickassets#44]
Hey,
I'm trying to get kickassets going, I'm pretty new to composer.
composer require silverstripe/kickassets seemed to update my composer.json file appropriately.  But as far as I can see kickassets isn't installed anywhere.
Can anyone point me in the right direction?
Thanks

**Comment by unclecheese** [comment]
There should be a folder named `kickassets/` right in the web root.

**Comment by tekurinui** [comment]
Something has gone weird environmentally.  It just swallows the require command and doesn't change the .json file or anything.

I checked out the project in a different place and it installed the module fine.  Not sure what's wrong with the env.

Thanks for coming back to me.
