### ISSUE TITLE
Feature request: remember last folder or search

### ISSUE THREAD

**Issue by jonom** [unclecheese/silverstripe-kickassets#47]
For repetitive tasks especially, but really any CMS workflow I think users would generally prefer for the state of the asset browser to persist in between accessing it. So if you navigate to a particular folder, or do a particular search and get a list of results then close the window, you get the same results when you open it again. It's very easy to return to home from any results page (one click) but it's arduous to return to a previous search or particular folder from the root directory.

**Comment by unclecheese** [comment]
Yeah, I think that's a good idea. We can just store the url in local storage. You know you can jump to a folder using the quick search at the top, right? That's a huge time saver.

**Comment by jonom** [comment]
> You know you can jump to a folder using the quick search at the top, right?

Yeah that's an awesome feature. I don't know if all of my older-school clients will remember to use it though and think this would be a useful addition either way - would still save a bit of typing.

**Comment by unclecheese** [comment]
I just put this into the master branch. Have a test!

**Comment by jonom** [comment]
Awesome! I've just tried it out on a site, I'm getting lots of errors but don't think it's related to this feature, just having trouble listing certain folders. Apart from that this seems to be working really well, the location and search is getting carried over between Uploadfield and Files interface which is awesome! Thanks so much for doing this.

**Comment by jonom** [comment]
Just tried again on a fresh install of SS3.3.1, works great for the most part but have found a couple of issues.

1. When you click the TinyMCE insert button it resets to root every time.
2. If you edit an item and then close the kick assets window while the edit form is open you can no longer open kick assets. I assume it tries to start you off at the edit form and returns a `I can't handle sub-URLs on class KickAssets.` error message. This is probably a pretty crippling bug - I had to call `localStorage.clear();` in the console while the kickassets window is closed to restore access.

**Comment by unclecheese** [comment]
Thanks, Jono. I've removed `localStorage` all together. I had forgotten that `kickassets-cms.js` was persistent through the session, so the url is just a local variable now.

Heaps of other fixes, too, including that routing issue.

Have another go?

**Comment by jonom** [comment]
Awesome, works great now! Think this is a big improvement for users, thanks.

Closed with https://github.com/unclecheese/silverstripe-kickassets/commit/56c9851e141d2d5d32b8603e74ed193725662fa6
