### ISSUE TITLE
error 404 because folderID passed = 'NaN'

### ISSUE THREAD

**Issue by lienajp** [unclecheese/silverstripe-kickassets#49]
Hi,

kickassets is not working when trying to add an image from the CMS.
I tried to find out what happened and achieved to find a walk around so I can at least use the module.
But it needs to be improved.

In kickassets.php I added the following test in the if sentence: OR $r->param('FolderID') == 'NaN' to avoid the process being broken. Now I don't know why the parameter is not passed correctly and I am ready to debug it further but don't know how.
 
 `	public function handleFolderContents(SS_HTTPRequest $r) {
		if(!$r->param('FolderID') OR $r->param('FolderID') == 'NaN') {
			$folder = Injector::inst()->get('Folder');
			$folder->Filename = ASSETS_DIR;
			error_log("folder name hase been set to " . $folder->Filename);
		}
		else {
			$folder = Folder::get()->byID($r->param('FolderID'));
		}
`
Philippe

**Comment by unclecheese** [comment]
Can you confirm that it works on a clean install? If so, can you identify any modules you're using that might be causing the issue?

**Comment by lienajp** [comment]
It's a clean install with the latest version of silverstripe 3.3.1
I also have the Translatable module installed and Kickassets.
Everything has been installed using composer.

Maybe, it is a regressive issue because when I specify a folder with setFolderName, the upload doesn't show me the requested folder but the root folder (assets).

`class Page extends SiteTree {

    private static $has_one = array('HeaderImage' => 'Image'
                                    );
    
    private static $db = array('Glyphicon' => 'Varchar');

    public function getCMSFields() {
        $fields = parent::getCMSFields();
        $LogoLib = new UploadField('HeaderImage','Header Image');
        $LogoLib->setFolderName('/Uploads/Headers');
        $fields->addFieldToTab('Root.Images', $LogoLib);
        $fields->addFieldToTab('Root.Main', TextField::create('Glyphicon', 'Glyphicon'), 'Content');
        
        return $fields;
    }

}
`

**Comment by unclecheese** [comment]
There's been a lot written about compatibility with the Translatable module. Did you see this? https://github.com/unclecheese/silverstripe-kickassets/pull/48

**Comment by lienajp** [comment]
This solves the problem. Thanks a lot Aaron.
