### ISSUE TITLE
Delete doesn't work if file is not selected

### ISSUE THREAD

**Issue by Friksel** [unclecheese/silverstripe-kickassets#54]
When hovering over a file, then clicking pencil icon, then choose 'delete', the file will not be deleted if that file is not happens to be selected. This is happening in both thumbnail- and list-mode.
(btw Clicking 'edit' from within the 'pencil-menu' IS working on an unselected file...)

**Comment by hoodweb** [comment]
Can confirm this on SS 3.4.1

**Comment by unclecheese** [comment]
Fixed in https://github.com/unclecheese/silverstripe-kickassets/commit/ff7e7b18697b5749dbe3b223c110d262f07d2e4b

**Comment by Friksel** [comment]
Nice. Thanks!
