### ISSUE TITLE
Can not select file on search

### ISSUE THREAD

**Issue by hpeide** [unclecheese/silverstripe-kickassets#61]
It seems like it's not possible to select a file from a search where the image do not appear on the first page.

Steps:
- UploadField - From files
- Search for a file
- Click on search result to select the image
- Click done

You will get an error if the image did'nt appear in the thumbnail list first page. If you click the search result after you have loaded (and scrolled to) the image, it will work fine.

**Comment by unclecheese** [comment]
This is fixed in https://github.com/unclecheese/silverstripe-kickassets/commit/d442caeb302a864a4c49464be242fd5ea52f6feb

**Comment by MattyBalaam** [comment]
I'm still seeing this issue with the latest code.

**Comment by MattyBalaam** [comment]
To clarify. If I do a search and the file is in the left hand pane, then I can select the item in the right.

However, if there are a lot of files, or it is in a subfolder, when I do the search the item in the right is not selectable. 

If I'm in a folder with a lot of files, then do a search for a file not yet loaded in the left it will not be selectable until I 'load more' to the point the file is in the left pane.

**Comment by mrgray** [comment]
Ditto. I think it's a bug that's been hanging around since 2015. I'll review the source code to see if I can find a fix, https://github.com/unclecheese/silverstripe-kickassets/issues/31.

**Comment by unclecheese** [comment]
Should be fixed in https://github.com/unclecheese/silverstripe-kickassets/commit/fdf1151f8203b6bd41604f792f16ea7e48f16ceb
